#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

timezone=$(timedatectl show --value --property=Timezone)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config Specific"
_fix_ldap

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

touch "/var/log/nginx/${domain}-error.log"

ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex='"PHP message: user \(name stripped-out\) authentication failure for Baikal" while reading response header from upstream, client: <HOST>'

#=================================================
# UPGRADE BAIKAL CONFIGURATION
#=================================================
ynh_script_progression "Upgrading the configuration file..."

path=${path%/}
ynh_config_add --template="baikal.yaml" --destination="$install_dir/config/baikal.yaml"

chmod 640 "$install_dir/config/baikal.yaml"
chown $app:$app "$install_dir/config/baikal.yaml"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
